### PR TITLE
Fix breaking bugs after merge with talgalili

### PR DESCRIPTION
**Pull request by Alanocallaghan**
Hi there, thankfully those bugs were fairly minor (should really have been caught during my testing!), I've now patched them. Cheers

### CODE REVIEW

**Comment by talgalili** [comment]
Great, thanks @Alanocallaghan. I'll give it a look and will get back to you.

**Comment by Alanocallaghan** [comment]
Tal I'd note that the second error you noticed previously (where `row_side_colors = mtcars[, 1]` is a difficult case, where the side_colors is a vector rather than a matrix or data.frame. I could allow this input but it will require checking that the dimensions of the inputs match up - something that will probably need doing soon anyway to avoid confusing errors for users, or worse, "silently wrong" outputs. 

If I get the chance I'll add that in, or you could do similarly

**Comment by Alanocallaghan** [comment]
Sorry I should say that this is due to R dropping dimensions when using the `[row, col]` notification without specifying `drop = FALSE`, ie `[row, col, drop = FALSE]`, such that rather than a matrix or df as input you get a column vector

**Comment by talgalili** [comment]
Hi @Alanocallaghan 

The latest pull still had several build errors.
One is since rainbow wasn't exported properly. See:
https://travis-ci.org/talgalili/heatmaply/builds/171586334
I moved to using colorspace:rainbow_hcl  and exported it. 
Another issue is that some parameters didn't have defaults (heatmap_layers in heatmaply.heatmapr), see:
https://travis-ci.org/talgalili/heatmaply/builds/171588792

I hope I've fixed all of them.

In the meantime, another issue - there seems to be inconsistency between heatmap.2 and heatmaply. I was able to create a simple example to demonstrate it. 

```r
x  <- as.matrix(datasets::mtcars)
# rc <- rainbow(nrow(x), start=0, end=.3)
# cc <- rainbow(ncol(x), start=0, end=.3)
rc <- colorspace::rainbow_hcl(nrow(x))

library(gplots)
library(viridis)
heatmap.2(x, trace = "none", col = viridis(100),
          RowSideColors=rc)

library(heatmaply)
heatmaply(x, seriate = "mean", 
          # RowSideColors=data.frame(rc))
          row_side_colors = data.frame(rc))

```


heatmap.2:

image

heatmaply:

image


Could you please have a look at this to see how to make them both give similar results?

**Comment by Alanocallaghan** [comment]
Sure thanks for fixing those! I'll have a look at these on Monday most likely

**Comment by talgalili** [comment]
Thanks @Alanocallaghan 
I appreciate your help, this looks like a very useful addition to the package.

**Comment by talgalili** [comment]
p.s.: I just finished fixing all the various errors (there were a few more, having to do with the .Rd files). Please make sure to fetch the most resent version before working on this further.

Cheers, 
Tal

**Comment by Alanocallaghan** [comment]
I had a quick look at this, the reason it's different is because in heatmap.2 it's plotting those colours directly, but in the side_color_plot it's being mapped to the color palette as a character vector (ie, `row_side_colors`  is expected to contain categories, not colors). I added the `row/col_color_palette` parameters to allow users to specify the colours used, but unfortunately I don't think it's really feasible or useful to allow users to pass in colors (the mouseover text is useless, for one!). Without digging too far into heatmap.2's functions, I imagine there will always be some difference in these plots given that 

I did however note that in your example (and any case where there is only one column in the side_colors) the axis text becomes the strange (0, 0.5, 1) rather than the column name of the input. The naive fix to this is to remove the axis text when this is the case, but I would prefer to actually solve it. 

I'll have another look tomorrow though

**Comment by talgalili** [comment]
Thanks @Alanocallaghan 

If you noticed I've added RowSideColors/ColSideColors parameters to heatmaply. Currently, they just pass their value to row_side_colors. The ideal solution would be that when the user uses them he/she would get the exact same result they did with heatmap.2, while when using row_side_colors they could pass some factor, and the behavior would be as it is now (finding colors based on the row_side_palette).
This would keep backward compatibility with heatmap.2 (which would help people use it), and also offer a more refined solution (for smarter hover text, as you suggest).

What do you think?

**Comment by Alanocallaghan** [comment]
I'm not sure how useful it really is given that the order of colours is abitrary and it's encouraging/allowing users to choose an option that's actually less useful/informative. At the same time maintaining compatibility/comparability with other major packages is important for users who test may many before choosing which to use. 

I'll have a think about how best to accomplish it in any case as it may involve a bit of refactoring

**Comment by talgalili** [comment]
:+1:

**Comment by Alanocallaghan** [comment]
I've added that to my fork, it was fairly straightforward. I've also added some code to suppress the creation of a new X11 device and to suppress the messages and warnings caused by the ggplotly(px/py) calls. I feel that warnings/messages should not be output when the function is operating as it is supposed to normally. I'll make another PR in the next few days

**Comment by talgalili** [comment]
Great, thanks.

**Pull request merged**
