### PR TITLE
Update README to include information how to port d3heatmap functions

### PR DESCRIPTION
**Pull request by evanbiederstedt**
* Additions to explain to users how to port their old `d3heatmap` code to `heatmaply`

Discussed here: 

https://github.com/yonicd/shinyHeatmaply/issues/28

### CODE REVIEW

**Comment by talgalili** [comment]
Merged, thanks.

**Comment by evanbiederstedt** [comment]
Naturally, feel free to add more details

Thanks, Evan

**Comment by talgalili** [comment]
Already merged. If you have suggestions for more changes - please make
another PR.
Thanks :)

**Comment by evanbiederstedt** [comment]
Sorry for the short message :)

What I mean to say is, feel free to add more details if you wish. What I wrote was somewhat of a first draft :)

I really appreciate the help with this---if nothing else, these details will allow me to remember how this works in the future. 

Best, Evan

**Pull request merged**
