### PR TITLE
Cellnote dots

### PR DESCRIPTION
**Pull request by Alanocallaghan**

### CODE REVIEW

**Comment by talgalili** [comment]
Just to check - so are we closing/giving up on this PR?

**Comment by Alanocallaghan** [comment]
This didn't seem to resolve the issue, but might be worth merging anyways.

**Comment by talgalili** [comment]
ok, please just make sure to update the NEWS and the DESCRIPTION if you end up merging this back to master (since we've just pushed a release to CRAN, I would wait with another push for at least a month)

**Comment by talgalili** [comment]
Hi @Alanocallaghan , Given that this branch has been open for a while (almost a year now), shall we just close it without merging?

**Comment by Alanocallaghan** [comment]
Sure

**Pull request closed without merging**
