### PR TITLE
Fix for #231

### PR DESCRIPTION
**Pull request by huzefaKhalil**
for plot_method="plotly", check if custom_hovertext exists. If so, it is displayed as is.

### CODE REVIEW

**Comment by Alanocallaghan** [comment]
I don't mind, but you should consider removing the trim whitespace setting in your text editor if you work on other peoples' repos often. Sometimes people will reject diffs that have a huge amount of whitespace (I know from experience).

**Comment by Alanocallaghan** [comment]
Thanks, I'll merge later

**Comment by huzefaKhalil** [comment]
No problem. Thanks.

**Comment by Alanocallaghan** [comment]
Thanks again @huzefaKhalil

**Pull request merged**
