### PR TITLE
Fix typo on README.md showing how to install dev prereqs

### PR DESCRIPTION
**Pull request by dan-fahey**
Original didn't combine package names into a vector.

### CODE REVIEW

**Comment by Alanocallaghan** [comment]
Is `devtools` required by one of the other packages?

**Comment by dan-fahey** [comment]
@Alanocallaghan No (see below), but it is needed for `devtools::install_github`.

```
> tools::package_dependencies("plotly")
$plotly
 [1] "ggplot2"      "tools"        "scales"       "httr"         "jsonlite"     "magrittr"     "digest"       "viridisLite"  "base64enc"   
[10] "htmltools"    "htmlwidgets"  "tidyr"        "hexbin"       "RColorBrewer" "dplyr"        "tibble"       "lazyeval"     "crosstalk"   
[19] "purrr"        "data.table"

> tools::package_dependencies("heatmaply")
$heatmaply
 [1] "plotly"       "viridis"      "ggplot2"      "dendextend"   "magrittr"     "reshape2"     "scales"       "seriation"    "utils"       
[10] "stats"        "grDevices"    "methods"      "colorspace"   "RColorBrewer" "htmlwidgets"  "webshot"      "gplots"       "assertthat"
```

**Comment by dan-fahey** [comment]
@Alanocallaghan Just checked, not in my session. Bigger picture solution might lie with the DESCRIPTION file depends/imports/suggests :smile: `devtools` should just be needed to install plotly and heatmaply from GitHub. The PR's not a big deal, just wanted to correct a typo while I had a minute because the package is great.
```
> library(purrr)

> work_smoothly_prereqs <- c("Rcpp","ggplot2","munsell","htmltools","DBI","assertthat",
+ "gridExtra","digest","fpc","TSP","registry","gclus","gplots" .... [TRUNCATED] 

> (unique_prereqs <- map(work_smoothly_prereqs, tools::package_dependencies) %>%
+   unlist() %>% unique())
 [1] "methods"     "utils"       "digest"      "grid"        "gtable"      "MASS"        "plyr"        "reshape2"    "scales"      "stats"      
[11] "tibble"      "lazyeval"    "colorspace"  "Rcpp"        "tools"       "grDevices"   "graphics"    "cluster"     "mclust"      "flexmix"    
[21] "prabclus"    "class"       "diptest"     "mvtnorm"     "robustbase"  "kernlab"     "trimcluster" "foreach"     "gtools"      "gdata"      
[31] "caTools"     "KernSmooth"  "stringi"     "magrittr"   

> "devtools" %in% unique_prereqs
[1] FALSE

> devtools::session_info()
Session info -----------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.3 (2017-11-30)
 system   x86_64, mingw32             
 ui       RStudio (1.1.414)           
 language (EN)                        
 collate  English_United Kingdom.1252 
 tz       Europe/London               
 date     2018-02-13                  

Packages ---------------------------------------------------------------------------------------------------------------------------------------------
 package    * version    date       source                               
 backports    1.1.2      2017-12-13 CRAN (R 3.4.3)                       
 base       * 3.4.3      2017-11-30 local                                
 compiler     3.4.3      2017-11-30 local                                
 datasets   * 3.4.3      2017-11-30 local                                
 devtools   * 1.13.4     2017-11-09 CRAN (R 3.4.3)                       
 digest       0.6.15     2018-01-28 CRAN (R 3.4.3)                       
 evaluate     0.10.1     2017-06-24 CRAN (R 3.4.3)                       
 graphics   * 3.4.3      2017-11-30 local                                
 grDevices  * 3.4.3      2017-11-30 local                                
 htmltools    0.3.6      2017-04-28 CRAN (R 3.4.3)                       
 knitr        1.19       2018-01-29 CRAN (R 3.4.3)                       
 magrittr     1.5        2014-11-22 CRAN (R 3.4.0)                       
 memoise      1.1.0      2017-04-21 CRAN (R 3.4.0)                       
 methods    * 3.4.3      2017-11-30 local                                
 purrr      * 0.2.4      2017-10-18 CRAN (R 3.4.2)                       
 Rcpp         0.12.15    2018-01-20 CRAN (R 3.4.3)                       
 rlang        0.1.6.9003 2018-02-13 Github (tidyverse/rlang@616fd4d)     
 rmarkdown  * 1.8        2017-11-17 CRAN (R 3.4.3)                       
 rprojroot    1.3-2      2018-01-03 CRAN (R 3.4.3)                       
 rstudioapi   0.7        2017-09-07 CRAN (R 3.4.2)                       
 stats      * 3.4.3      2017-11-30 local                                
 stringi      1.1.6      2017-11-17 CRAN (R 3.4.2)                       
 stringr      1.2.0      2017-02-18 CRAN (R 3.4.3)                       
 tools        3.4.3      2017-11-30 local                                
 usethis    * 1.2.0.9000 2018-02-07 Github (r-lib/usethis@42c19e4)       
 utils      * 3.4.3      2017-11-30 local                                
 withr        2.1.1.9000 2018-02-13 Github (jimhester/withr@df18523)     
 workflowr  * 0.10.2     2018-02-07 Github (jdblischak/workflowr@003de40)
 yaml         2.1.16     2017-12-12 CRAN (R 3.4.3)
```

**Comment by Alanocallaghan** [comment]
Much appreciated don't get me wrong :+1: I was just afraid it would break the README, but I see that `devtools` is installed manually afterwards anyway.

**Pull request merged**
