### PR TITLE
Adds height/width arguments to plotly methods

### PR DESCRIPTION
**Pull request by cole-johanson**
Closes [#86](https://github.com/talgalili/heatmaply/issues/86)

`heatmaply(mtcars, height=1000, width = 400)`

### CODE REVIEW

**Comment by talgalili** [comment]
@cole-johanson  - could you pleaes share a screenshot of the behavior before and after your fix?

**Comment by cole-johanson** [comment]
@talgalili, see below. 

```
heatmaply(mtcars, plot_method='plotly', height=400, width=200)
heatmaply(mtcars, plot_method='ggplot', height=400, width=200)
```

ggplot before: 
before_ggplot

ggplot after: 
after_ggplot

plotly before: 
before_plotly

plotly after: 
after_plotly

**Comment by alanocallaghan** [comment]
Thanks, sorry I forgot about this for so long!

**Comment by talgalili** [comment]
Thanks @alanocallaghan !
Could you please update the NEWS file with the updated details so I could release a new version?

**Pull request merged**
