### PR TITLE
Allow ordering of side colors via levels

### LINKED ISSUE #138: How to arrange the order of column annotation?
Hi Dev,

As title, is it possible to arrange the order of column annotation what i expect?
Thanks!
--
WM

### PR DESCRIPTION
**Pull request by Alanocallaghan**
Resolve #138

### CODE REVIEW

**Comment by talgalili** [comment]
Thanks Alan.

**Comment by Alanocallaghan** [comment]
Cheers, will update NEWS etc when I've checked it properly

**Comment by talgalili** [comment]
Great. Also, I think everything can go into version 0.14.0, since it was not yet released to CRAN.

**Comment by talgalili** [comment]
I've now pushed heatmaply 0.14.0 to CRAN.

**Pull request merged**
